---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gc-service
  labels:
    name: gc-service
    namespace: default
spec:
  selector:
    matchLabels:
      name: gc-service
  template:
    metadata:
      labels:
        name: gc-service
        plane: control
    spec:
      containers:
        - name: app
          image: gcr.io/pl-pixies/demos/go_garbage_collection_image:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gc-service
  labels:
    name: gc-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: gc-service
