---
# Adapted from the example in this repo: https://github.com/kubernetes-sigs/custom-metrics-apiserver
apiVersion: v1
kind: Namespace
metadata:
  name: px-custom-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: px-custom-metrics:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: px-custom-metrics-apiserver
  namespace: px-custom-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: px-custom-metrics-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: px-custom-metrics-apiserver
  namespace: px-custom-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: px-custom-metrics-apiserver
  name: px-custom-metrics-apiserver
  namespace: px-custom-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: px-custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: px-custom-metrics-apiserver
      name: px-custom-metrics-apiserver
    spec:
      serviceAccountName: px-custom-metrics-apiserver
      containers:
      - name: px-custom-metrics-apiserver
        image: gcr.io/pixie-oss/pixie-dev/demo/custom-k8s-metrics-api:0.0.1
        args:
        - /adapter
        - --secure-port=6443
        env:
        - name: PX_CLOUD_ADDR
          value: withpixie.ai:443
        - name: PX_CLUSTER_ID
          valueFrom:
            secretKeyRef:
              name: px-credentials
              key: px-cluster-id
        - name: PX_API_KEY
          valueFrom:
            secretKeyRef:
              name: px-credentials
              key: px-api-key
        ports:
        - containerPort: 6443
          name: https
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /tmp
          name: temp-vol
      volumes:
      - name: temp-vol
        emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: px-custom-metrics-resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: px-custom-metrics-resource-reader
subjects:
- kind: ServiceAccount
  name: px-custom-metrics-apiserver
  namespace: px-custom-metrics
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: px-custom-metrics-apiserver
  namespace: px-custom-metrics
---
apiVersion: v1
kind: Service
metadata:
  name: px-custom-metrics-apiserver
  namespace: px-custom-metrics
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: px-custom-metrics-apiserver
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: px-custom-metrics-apiserver
    namespace: px-custom-metrics
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
spec:
  service:
    name: px-custom-metrics-apiserver
    namespace: px-custom-metrics
  group: custom.metrics.k8s.io
  version: v1beta2
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 200
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: px-custom-metrics-server-resources
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: px-custom-metrics-resource-reader
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpa-controller-px-custom-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: px-custom-metrics-server-resources
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
