---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: px-metrics
  name: px-metrics
  namespace: px-metrics
spec:
  selector:
    matchLabels:
      name: px-metrics
  template:
    metadata:
      labels:
        name: px-metrics
        plane: control
    spec:
      containers:
        - name: app
          image: gcr.io/pixie-oss/pixie-dev/demo/argo-rollouts-demo:latest
          env:
          - name: PX_CLOUD_ADDR
            value: withpixie.ai:443
          - name: PX_CLUSTER_ID
            valueFrom:
              secretKeyRef:
                name: px-credentials
                key: px-cluster-id
          - name: PX_API_KEY
            valueFrom:
              secretKeyRef:
                name: px-credentials
                key: px-api-key
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: px-metrics
  name: px-metrics
  namespace: px-metrics
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: px-metrics
